FROM python:3

ENV PYTHONIOENCODING=UTF-8
ENV PIPENV_VENV_IN_PROJECT=1

WORKDIR /project

COPY Pipfile.lock Pipfile ./src ./

RUN pip install pipenv && pipenv install --system --deploy --ignore-pipfile

CMD scrapy crawl tesco

