"""create fk review

Revision ID: 8c885d4409ca
Revises: init3
Create Date: 2020-07-17 23:04:48.370862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c885d4409ca'
down_revision = 'init3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('review_ibfk_1', 'review', 'product', ['product_id'], ['product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_ibfk_1', 'review', type_='foreignkey')
    # ### end Alembic commands ###
