"""create table review

Revision ID: init3
Revises: init2
Create Date: 2020-07-17 22:57:48.553247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'init3'
down_revision = 'init2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('review')
    # ### end Alembic commands ###
