"""create table product

Revision ID: init
Revises: 
Create Date: 2020-07-17 22:51:54.992742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'init'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('image_url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('name_and_address', sa.String(length=1000), nullable=True),
    sa.Column('return_address', sa.String(length=1000), nullable=True),
    sa.Column('net_contents', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
